version: '2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        container_name: nginx_server
        image: nginx:alpine
        restart: always

    apache:
        depends_on:
            - reverseproxy
        container_name: apache_reverse_proxy
        build: app/
        restart: always

    mongo:
        container_name: mongo-backend
        image: mongo
        ports: 
        - "27017:27017"
        volumes: 
        - ./db_volume:/data/db